# See 
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# for ideas.

# Project information
site_name: "uchronia - N-dim time series"
# site_url: https://squidfunk.github.io/mkdocs-material/
site_author: "Jean-Michel Perraud"
site_description: >-
  This package is for handling N-dimensional time series for 
  temporal ensembles simulations and forecasts, e.g. 
  hydrologic forecasts

# Repository
repo_name: csiro-hydroinformatics/uchronia-time-series
repo_url: https://github.com/csiro-hydroinformatics/uchronia-time-series

docs_dir: './docs'

# Copyright
copyright: Copyright &copy; 2016 - 2022 CSIRO

theme:
  # name: "readthedocs"
  name: "material"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  # Default values, taken from mkdocs_theme.yml
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
  # minify seems advanced. https://squidfunk.github.io/mkdocs-material/customization/#theme-development  
  # - minify:
  #   minify_html: true



# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
     anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.keys
  # - pymdownx.magiclink:
  #    repo_url_shorthand: true
  #    user: csiro-hydroinformatics
  #    repo: pyuchronia
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  # - Applications: usage-and-applications.md
  - API Doc:
    - Module classes: classes-module.md
    - Module data_set: data_set-module.md
    - Module internals: internals-module.md
    - Module sample_data: sample_data-module.md
    - Module time_series: time_series-module.md
    - Module utils: utils-module.md
    - Module const: const-module.md
  - Appendix:
    - Developer Notes: tech_notes.md

