---
title: "Ensemble time series - overview"
author: "Jean-Michel Perraud"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Ensemble time series - overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Ensemble time series - overview
=================

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.extra='style="display:block; margin: auto"', fig.align="center", fig.width=10, fig.height=8, dev='png')
```

```{r, eval=FALSE, include=FALSE}
library(swiftdev)
thisPkgDir <- file.path(find_env_SwiftSrcPath(), 'R/pkgs/swift')
if(file.exists(thisPkgDir))
{
  setwd(file.path(thisPkgDir, 'vignettes'))
  purlVignettes('.','..')
}
```

# About this document

This document was generated from an R markdown file on `r as.character(Sys.time())`.

# Elaboration

```{r}
prepend_path() ; devmode() ; prepend_rlibpath() ; library(uchronia)
docDataPath <- Sys.getenv('SWIFT_SAMPLE_DATA_DIR') # swift::sampleDataDir()
```

SWIFT includes facilities to access time series from a "library", akin to what you would do to manage books.

```{r eval=has_data}
dataLibraryFile <- file.path(system.file('data', package='swift'), 'time_series_library.yaml')
upperMurrayDataPath <- file.path(docDataPath, 'UpperMurray')
stopifnot(dir.exists(upperMurrayDataPath))

dataLibrary <- getEnsembleDataSet(dataLibraryFile, upperMurrayDataPath)
dataIds <- GetEnsembleDatasetDataIdentifiers_R(dataLibrary)
print(GetEnsembleDatasetDataSummaries_R(dataLibrary))
```
