# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: matrix-build

on:
  push:
    branches: [ "testing" ]
  #pull_request:
  #  branches: [ "testing" ]

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        # python-version: ["3.9", "3.10"]
        # exclude:
        #   - os: macos-latest
        #     python-version: "3.10"
        #   - os: windows-latest
        #     python-version: "3.10"
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Check out c-interop repo
      uses: actions/checkout@v3
      with:
        repository: csiro-hydroinformatics/c-interop
        ref: testing
        path: c-interop
        # token: ${{ secrets.my_pat }}
    - name: Install c-interop C++ headers
      run: |
        cd c-interop
        mkdir -p build && cd build
        cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
        sudo make install
